name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 3 * * 1' # Lunes a las 3 AM

jobs:
  trivy:
    name: Run Trivy Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Escaneo de dependencias (Node.js, etc.)
      - name: Run Trivy FS scan (SARIF)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      # Verificar que el archivo SARIF se generó
      - name: Check SARIF file
        run: |
          echo "Verificando archivo SARIF..."
          ls -lh trivy-results.sarif

      # Subir resultados al panel de seguridad
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      # Mostrar un resumen legible en consola
      - name: Show Trivy summary
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
