name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 3 * * 1'  # Escaneo automático cada lunes a las 3 AM

jobs:
  trivy-scan:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write  # Necesario para subir resultados a GitHub Security
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Escaneo de vulnerabilidades en dependencias (Node.js, npm, etc.)
      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      # Subir resultados al panel de seguridad de GitHub
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Show summary in console
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
